elems:

  - src: elems/xresources/main$
    dst: '<%= get_var! :"xorg.xresources.main" %>'
    only: f?xorg

  - src: elems/xresources/colorschemes/(.+)$
    dst: '<%= get_var! :"xorg.xresources.custom_dir", type: :directory %>/colorschemes/<1>'
    only: f?xorg

  - src: elems/(xorg\.conf\.d/[0-9]+-apple\.conf)$
    dst: /etc/X11/<1>
    only: f?xorg && f?macbook

  - src: elems/(xorg\.conf\.d/[0-9]+-wacom\.conf)$
    dst: /etc/X11/<1>
    only: f?xorg && f?wacom


# vim: set filetype=eruby.yaml :
